polls/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from polls import views

URLPattern = [
    path('',views.index)
]

votewebG/urls.py
from django import urls

from django.contrib import admin
from django.urls import path,include
from polls import views,autocomplete
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('',views.frontdex),
  path('index',views.index, name='index'),
    path('deletevote/<str:election_id>/', views.deletevote, name='deletevote'),
    path('editvote/<str:election_id>/', views.editvote,name='editvote'),
    path('managevote',views.managevote, name="managevote"),
    path('managepoll', views.managepoll, name='managepoll'),
    path('polledit/<str:poll_id>/', views.polledit,name='polledit'),
    path('polldelete/<str:poll_id>/', views.polldelete, name='polldelete'),
    path('manageadmin', views.manageadmin, name='manageadmin'),
    path('edituser/<str:user_id>/', views.edituser,name='edituser'),
    path('report', views.report),
    path('register',views.register, name='register'),
    path('loginform',views.loginform, name='loginform'),
    path('logoutUser',views.logoutUser, name='logoutUser'),
    path('',include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
#front end
    path('frontdex', views.frontdex, name='frontdex'),
    path('createvote', views.createvote, name='createvote'),
    path('vote', views.vote, name='vote'),
    path('createpoll', views.PollView.as_view(), name='createpoll'),
    path('editpoll/<int:id>/', views.PollView.as_view(), name='editpoll'),
    path('deletepoll/<int:id>/', views.deletepoll, name='deletepoll'),
    path('letvote/<str:poll_id>/', views.letvote, name='letvote'),
    path('letpoll/<str:poll_id>/', views.letpoll, name='letpoll'),
    path('pollresult/<str:poll_id>/', views.pollresult, name='pollresult'),
    path('createelect', views.ElectView.as_view(), name='createelect'),
    path('editelect/<int:id>/', views.ElectView.as_view(), name='editelect'),
    path('letelect/<str:election_id>/', views.letelect, name='letelect'),
    path('electresult/<str:election_id>/', views.electresult, name='electresult'),
    path('deleteelect/<int:id>/', views.deleteelect, name='deleteelect'),    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractBaseUser,BaseUserManager,UserManager
from django.db import connection,transaction,models
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.http import HttpResponse, HttpResponseRedirect, Http404
from votewebG import settings
from datetime import datetime
from django.utils import timezone



#--------------------------------User --Zone -----------------------------------------------

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='all_user', max_length=255, null=True, blank=True)

    def __str__(self):
        return "{0} - {1}".format(self.user.username)



class UserManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(profile__designation="User")

class CustomUser(User):
    class Meta:
        ordering = ("username",)
        proxy = True

    objects = UserManager()
    
    def full_name(self):
        return self.first_name + " - " + self.last_name


@receiver(post_save, sender=User)
def user_is_created(sender, instance, created, **kwargs):
    print(created)
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()


from django.contrib.auth.models import User

@property
def full_name(self):
    return "{} {}".format(self.first_name, self.last_name)

User.add_to_class('full_name', full_name)

#-----------------------------END User -- Zone -----------------------------------------------
#-----------------------------Poll -- Zone----------------------------------------------------
class ObjectTracking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
 

class Comment(models.Model):
    text = models.TextField(null=False, blank=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.text[:20]

class Tag(ObjectTracking):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = []

class QuestionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="open")

    def all_objects(self):
        return super().get_queryset()

    def inactive(self):
        durate= self.vote_end <= datetime.now() <= self.vote_start
        return durate.all_objects().filter(status='Close')



class Poll(ObjectTracking):
    STATUS = (
        ("OPEN", "Open"),
        ("CLOSE", "Close"),
    )
    question = models.TextField()
    status = models.CharField(choices=STATUS,default='OPEN', max_length=10)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    poll_start = models.DateTimeField(null=True, blank=True,default=datetime.now())
    poll_end = models.DateTimeField(null=True, blank=True)
    tags = models.ManyToManyField(Tag)

    comments = GenericRelation(Comment, related_name="question")

    objects = QuestionManager()


    def __str__(self):
        return self.question
    
    @property
    def choices(self):
        return self.choice_set.all()
    


class Choice(models.Model):
    question = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    @property
    def votes(self):
        return self.answer_set.count()


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    comments = GenericRelation(Comment, related_name="answer")

    def __str__(self):
        return self.user.first_name + ' --has ans-- ' + self.choice.text
#-------------------------END Poll--Zone--------------------------------------------------
#--------------------------- Election -- Zone --------------------------------------------

class Election(ObjectTracking):
    TYPES = (
        ("Pl", "Plurality"),
        ("Pr", "Preferential"),
    )
    STATUS = (
        ("OPEN", "Open"),
        ("CLOSE", "Close"),
    )
    name = models.CharField(max_length=120,null=False, blank=False)
    status = models.CharField(choices=STATUS,default='OPEN', max_length=10)
    created_by = models.ForeignKey(User, related_name="Creator",null=True, blank=True, on_delete=models.CASCADE)
    allowed_voters = models.ManyToManyField(settings.DJANGO_ELECT_USER_MODEL, related_name="Voter",blank=True)
    introduction=models.TextField(null=True, blank=True)
    picture=models.ImageField(upload_to="vote_pic",null=False, blank=False)
    vote_start = models.DateTimeField(null=False, blank=False,default=datetime.now())
    vote_end = models.DateTimeField(null=False, blank=False)
    type = models.CharField(max_length=2, blank=True, choices=TYPES,default="Pl")

    objects = QuestionManager()

    def __str__(self):
        return self.name

    def voting_allowed_for_user(self, user):
        """
        Returns True if not is between vote_start and vote_end, inclusive,
        and given user is in allowed_voters and user hasn't already voted.
        """
        return (self.voting_allowed() and not self.has_voted(user) and
            (self.allowed_voters.count() == 0 or
            self.allowed_voters.filter(id=user.id)))

    @property
    def candys(self):
        return self.candidate_set.all()


class Candidate(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=65)
    last_name = models.CharField(max_length=65)
    image=models.ImageField(upload_to='candy_pic')
    biography = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.election.name + ": " +self.first_name + " " + self.last_name

    @property
    def voted(self):
        return self.voted_set.count()


class Voted(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    candy = models.ForeignKey(Candidate, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name + '-- has choose --' + self.candy.first_name
    
    
    
class VotePreferential(models.Model):
    """
    Vote for a candidate on a preferential ballot (i.e. Ballot.type="Pr")
    """
    vote = models.ForeignKey(Voted, related_name="preferentials", null=True, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    point = models.PositiveSmallIntegerField()

    def __unicode__(self):
        return "%s vote, %i points for %s" % (self.vote, self.point,
                                              self.candidate.get_name())


class VotePlurality(models.Model):
    """
    Vote for a candidate on a plurality ballot (i.e. Ballot.type="Pl")
    """
    vote = models.ForeignKey(Voted, related_name="pluralities", null=True, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)

    def __unicode__(self):
        return "%s vote for %s" % (self.vote, self.candidate.get_name())

polls/templates/polls/createelect.html
{% extends 'polls/frontdex.html' %}
{% load static %}
{% load user_tags %}
{% block content %}


<header class="d-flex justify-content-center py-3 border-bottom">
          
            <li class="nav-linv px-2 link-active">ELECTION VOTE</a></li>
            
          </ul>

        </header>
</div>


<!-- Navigation-->
<div class="banner-wall">
<img class="img-tent" src="{% static 'dist/img/peaceful.gif' %}">
        <div class="modal-contentv">
    <div class="modal-headerv">
<ul class="backen">
            <bli class="nav-item">
        <a href="/createvote">
          <i class="vote-icon fas fa-arrow-circle-left"></i>
        </a>
      </bli>
        
      <h2 class="center">สร้างโหวตของคุณ..</h2></ul>
    </div>
    <div class="modal-bodyv text-dark">
    <ul class="list-group" id="style-8" style="height: 400px !important; overflow: scroll; overflow-x: hidden; ">
      <form class="vform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      
      
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">ชื่อโหวต</p></div>
            <div class="w3-rest">
                {{elect_form.name}}
            </div>
          </div>
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">รูปภาพ</p></div>
            <div class="w3-rest">
                {{elect_form.picture }}
            </div>
          </div>
        <div class="w3-half w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">วันเริ่มต้น</p></div>
            <div class="w3-rest">
                {{elect_form.vote_start }}
            </div>
          </div>
        <div class="w3-half w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">วันสิ้นสุด</p></div>
            <div class="w3-rest">
                {{elect_form.vote_end }}
            </div>
          </div>
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-medium">รายละเอียด</p></i></div>
            <div class="w3-rest">
                {{elect_form.introduction }}
            </div>
          </div>
        
          
          <table id="id_forms_table" class="table form-table table-bordered table-sm" enctype="multipart/form-data">
          
                        <tbody>
                            {{ formset.management_form }} 
                            {% for form_data in candy_forms %}
                                <tr id="{{ form.prefix }}-row" class="dynamic-form">
                                    <td style="width:20%">
                                        ชื่อ:{{ form_data.first_name }}
                                    </td >
                                    <td style="width:20%">
                                        นามสกุล:{{ form_data.last_name }}
                                    </td>
                                    <td style="width:25%">
                                    	รูปภาพ:{{ form_data.image }}
                                    </td>
                                    <td>
                                    	รายละเอียด:{{ form_data.biography }}
                                    </td>
                                </tr>
                            {% endfor %}
    
           </table>
        <br>
        <input class="btn btn-danger" type="submit" name="Create vote" value="Create Election" >
    </form>
                    
            
    
    
</div>
<!-- Section-->


        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/createpoll.html
{% extends 'polls/frontdex.html' %}
{% load static %}
{% load user_tags %}
{% block content %}


<header class="d-flex justify-content-center py-3 border-bottom">
          
            <li class="nav-linv px-2 link-active">POLL VOTE</a></li>
            
          </ul>

        </header>
</div>


<!-- Navigation-->
<div class="banner-wall">
<img class="img-tent" src="{% static 'dist/img/peaceful.gif' %}">
        <div class="modal-contentp">
    <div class="modal-headerp">
    <ul class="backen">
      <bli class="nav-item">
        <a href="/createvote">
          <i class="vote-icon fas fa-arrow-circle-left"></i>
        </a>
      </bli>
      <h2 class="center">สร้างคำถามของคุณ...</h2></ul>
    </div>
    <div class="modal-bodyp text-dark">
    
      <form class="pform" method="POST" enctype="multipart/form-data" align="center">
        {% csrf_token %}

                        <div class="center">
                            <div class="form-group">
                                <label for="question"><h2>คำถาม...</h2></label>
                                {{poll_form.question}}
                            </div>
                        </div>
                    
        <table class="table table-bordered table-light" >
            {% for form in choice_forms %}
            <tr><th><label for="id_question">ตัวเลือก:</label></th><td>{{form.text}}</td></tr>
            {% endfor %}
        </table>
                </div>
        <input class="w3-button w3-section w3-blue w3-ripple w3-padding" type="submit" name="Create vote" value="Create Polls" >
    </form>
   
    </div>

</div>
<!-- Section-->


        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/editelect.html
{% extends 'polls/frontdex.html' %}
{% load static %}
{% load user_tags %}
{% block content %}


<header class="d-flex justify-content-center py-3 border-bottom">
          
            <li class="nav-linv px-2 link-active">ELECTION VOTE</a></li>
            
          </ul>

        </header>
</div>


<!-- Navigation-->
<div class="banner-wall">
<img class="img-tent" src="{% static 'dist/img/peaceful.gif' %}">
        <div class="modal-contentv">
    <div class="modal-headerv">
<ul class="backen">
            <bli class="nav-item">
        <a href="/vote">
          <i class="vote-icon fas fa-arrow-circle-left"></i>
        </a>
      </bli>
        
      <h2 class="center">สร้างโหวตของคุณ..</h2></ul>
    </div>
    <div class="modal-bodyv text-dark">
    <ul class="list-group" id="style-8" style="height: 400px !important; overflow: scroll; overflow-x: hidden; ">
      <form class="vform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      
      
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">ชื่อโหวต</p></div>
            <div class="w3-rest">
                {{elect_form.name}}
            </div>
          </div>
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">รูปภาพ</p></div>
            <div class="w3-rest">
                {{elect_form.picture }}
            </div>
          </div>
        <div class="w3-half w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">วันเริ่มต้น</p></div>
            <div class="w3-rest">
                {{elect_form.vote_start }}
            </div>
          </div>
        <div class="w3-half w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-large">วันสิ้นสุด</p></div>
            <div class="w3-rest">
                {{elect_form.vote_end }}
            </div>
          </div>
        <div class="w3-row w3-section">
          <div class="w3-col" style="width:100px"><p class="w3-medium">รายละเอียด</p></i></div>
            <div class="w3-rest">
                {{elect_form.introduction }}
            </div>
          </div>
     
          
          <table id="id_forms_table" class="table form-table table-bordered table-sm" enctype="multipart/form-data">
          
                        <tbody>
                            {{ formset.management_form }} 
                            {% for form_data in candy_forms %}
                                <tr id="{{ form.prefix }}-row" class="dynamic-form">
                                    <td style="width:20%">
                                        ชื่อ:{{ form_data.first_name }}
                                    </td >
                                    <td style="width:20%">
                                        นามสกุล:{{ form_data.last_name }}
                                    </td>
                                    <td style="width:25%">
                                    	รูปภาพ:{{ form_data.image }}
                                    </td>
                                    <td>
                                    	รายละเอียด:{{ form_data.biography }}
                                    </td>
                                </tr>
                            {% endfor %}
    
           </table>
        <br>
        <button type="submit" class="btn btn-danger float-right">Create Election</button>
    </form>
                    
            
    
    
</div>
<!-- Section-->


        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/editvote.html
{% extends 'polls/test.html' %}
{% load static %}
{% block content %}
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/a.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
      </div>     
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item d-none d-sm-inline-block">
               <br>
               <br>
          </li>
          <li class="nav-item">
               
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-users"></i>
              <p>
                จัดการรายการโหวต
              </p>
            </a>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
 
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="manageuser">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark"><b>แก้ไขข้อมูล: {{ upuser.usfname }}</b></h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="row">
                  <div class="col-sm-9">
                    <div class="box-body">

      <form class="modal-body" action="" method="POST">
        {% csrf_token %}
        Vote Name:{{form.name}}<br>
        Created By:{{upvote.created_by.first_name}}<br>
        Change Image:<img src="{{upvote.picture.url}}" style="width:280px; height:150px"><br>
        Vote Details:{{form.introduction}}<br>
         
      <div class="modal-footer">
        <a href="{% url 'managevote' %}" class="btn btn-secondary">
         Cancel
        </a>
        <input type="submit" value="Save Change" name="Edit" class="btn btn-primary">
      </div>
     </form> 
   
  
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
    </div>
  </div><!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->
{% endblock %}

polls/templates/polls/electresult.html
{% extends 'polls/frontdex.html' %}
{% load static %}
{% load user_tags %}
{% block content %}


<header class="d-flex justify-content-center py-3 border-bottom">
          
            <li class="nav-linv px-2 link-active">Election Result</a></li>
            
          </ul>

        </header>
</div>


<!-- Navigation-->
<div class="banner-wall">
    <img class="img-tent" src="{% static 'dist/img/rain.gif' %}">
        <div class="centered resultp">
        <h1 class="mb-5 text-center ">ผลโหวต: <h class="display-4">{{election.name}}</h></h1>
          
          <ul class="list-poll center">
    {% for candy in election.candys %}
        <li class="list-group-item">
            <span class="badge w3-yellow float-right">{{candy.voted}}</span>
            {{candy.first_name}} {{candy.last_name}}
        </li>
        <!-- <p> ({{choice.votes}})</p> -->
        {% empty %}
        <div class="list-group-result">There is no chice available for this question.</div>
        {% endfor %}
        <br>
        <a class="btn btn-danger" href="/vote">Back To Polls</a> 
        
    </ul>
    <br>
    <div class="col-md-12"><b>Created by: </b> {{election.created_by.first_name}}</div>

</div>






  <!-------------------END Prev-Next----------------------> 
  <br><br><br>
   {% endblock %}
  
 
     


  

polls/templates/polls/formset.html
{% load crispy_forms_tags %}
{% load static %}
<table>
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="{% static 'dist/js/jquery.formset.js' %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

polls/templates/polls/letpoll.html
{% extends 'polls/frontdex.html' %}
{% load static %}
{% load user_tags %}
{% block content %}


<header class="d-flex justify-content-center py-3 border-bottom">
          
            <li class="nav-linv px-2 link-active">POLL VOTE</a></li>
            
          </ul>

        </header>
</div>


<!-- Navigation-->
<div class="banner-wall">
<img class="img-tent" src="{% static 'dist/img/rain.gif' %}">
        
    <div class="centered ">
        <div class="panelp panel-default">
            <div class="panel-heading">
                <ul class="backen col-12 col-md-auto mb-2 ">
            <bli class="nav-item">
        <a href="/vote">
          <i class="vote-icon fas fa-arrow-circle-left"></i>
        </a>
      </bli>
            </div>
        </ul>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <h2 >{{ question.question }}</h2>
                    </div>
                </div>

                <form method="POST" action="{% url 'letpoll' question.id %}">
        {% csrf_token %}
    {% for choice in question.choices %}
        <div class="radio">
            <label>
                <input type="radio" name="choice" value="{{choice.id}}">
                {{choice.text}}
            </label>
        </div>
    {% empty %}
        <p>There is no chice available for this question.</p>
    {% endfor %}
        <input class="w3-button w3-section w3-blue w3-ripple w3-padding" type="submit" name="Create vote" value="vote" >
    </form>
            
    
    
</div>
<!-- Section-->


        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/loginform.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>ERP VOTE | Login</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/loginstlye.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body>
<div class="wrapper" id="id02">
    <li class="nav-item">
        <a href="/frontdex" class="nav-link">
          <i class="nav-icon fas fa-arrow-circle-left"></i>
        </a>
      </li>
	<div class="container">
        
		<h1>ลงทะเบียน เข้าใช้งาน </h1>
	    <div class="imgcontainer">
            <img src="{% static 'dist/img/SWUVOTE_logo.png' %}" alt="Avatar" class="avatar">
        </div>
        <form class="form" action="loginform" method="POST">  
          {% csrf_token %}      
            {{form.username}}
            {{form.password}}
           
            <input class="sub" type="submit" value="Login">

            {% for message in massages %}
               <p id="message">{{messages}}</p>
               {% endfor %}

              <div class="mt-4">
                <div class="d-flex justify-content-center links">
                  Don't have an account? <a href="/register" class="ml-2">Sign Up</a>
                </div>
            
              </div>
          
          </form>
	</div>
	<!--bubble wallpaper-->
        <div class="bubble x1"></div>
        <div class="bubble x2"></div>
        <div class="bubble x3"></div>
        <div class="bubble x4"></div>
        <div class="bubble x5"></div>
        <div class="bubble x6"></div>
        <div class="bubble x7"></div>
        <div class="bubble x8"></div>
        <div class="bubble x9"></div>
        <div class="bubble x10"></div>
    <!--END bubble -->
</div>
<script>
//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Buasri ID';
form_fields[2].placeholder='Password';


for (var field in form_fields){	
form_fields[field].className += ' form-control'


}
</script>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>